
- name: Spin up managed hosts
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Remove keys from known_hosts, if they exist
      block:
        - name: Remove keys from known_hosts, if they exist
          register: command_result
          command: ssh-keygen -f '/home/ansible-user/.ssh/known_hosts' -R {{ item }}
          with_items:
            - ansible-host-1
            - ansible-host-2
            - ansible-host-3
            - ansible-host-4
        - debug:
            msg: The known_hosts file was cleansed successfully

      rescue:
        - debug:
            msg: "ERROR: {{ command_result }}"
        - debug:
            msg: "SUCCESS: {{ command_result }}"


    - name: Spin up managed hosts
      block:
        - name: docker run
          register: command_result
          command: docker run --name {{ item }} -it -d ansible-host
          with_items:
            - ansible-host-1
            - ansible-host-2
            - ansible-host-3
            - ansible-host-4
        - debug:
            msg: The containers spun up corectly.

      rescue:
        - debug:
            msg: "ERROR: {{ command_result }}"
        - debug:
            msg: "SUCCESS: {{ command_result }}"


    - name: Add managed host containers keys to known_hosts
      block:
        - name: Add managed host containers keys to known_hosts
          register: command_result
          command: ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts
          with_items:
            - ansible-host-1
            - ansible-host-2
            - ansible-host-3
            - ansible-host-4
        - debug:
            msg: The keys were added to known_hosts correctly.
        - debug:
            msg: "SUCCESS: {{ command_result }}"

      rescue:
        - debug:
            msg: "ERROR: {{ command_result }}"


